# Generated by scripts/homebrew_formula.py from published release checksums.
class Zero < Formula
  desc "Operator terminal for self-custodial onchain operations"
  homepage "https://getzero.dev"
  version "0.1.2"
  license "Apache-2.0"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/zero-intel/zero/releases/download/v0.1.2/zero-macos"
    sha256 "68262ded7cb7b1add978cdf292dab2d34c20246c711e0dbfb14f50735020e3d3"
  elsif OS.mac?
    odie "ZERO currently ships an arm64 macOS binary; use install.sh or build from source on Intel macOS"
  else
    url "https://github.com/zero-intel/zero/releases/download/v0.1.2/zero-linux"
    sha256 "b735e19420994ab4241698df9aa500863e2c4fdcda2ba3c02ad7ebbe3505d9d9"
  end

  def install
    bin.install cached_download => "zero"
    chmod 0755, bin/"zero"
  end

  def caveats
    <<~EOS
      Installs the ZERO CLI only. The public runtime defaults to paper mode.
      Release docs: https://github.com/zero-intel/zero/blob/main/docs/release.md
      Safety model: https://github.com/zero-intel/zero/blob/main/docs/safety-model.md
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zero --version")
  end
end
