# Generated by scripts/homebrew_formula.py from published release checksums.
class Zero < Formula
  desc "Operator terminal for self-custodial onchain operations"
  homepage "https://getzero.dev"
  version "0.1.1"
  license "Apache-2.0"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/zero-intel/zero/releases/download/v0.1.1/zero-macos"
    sha256 "7dfbcd7acba04dece4d0c4dcee2e72213c191bf0cb9c6b432f5e663d87bd4b0f"
  elsif OS.mac?
    odie "ZERO currently ships an arm64 macOS binary; use install.sh or build from source on Intel macOS"
  else
    url "https://github.com/zero-intel/zero/releases/download/v0.1.1/zero-linux"
    sha256 "2c31ca36e274c44b55efa5bcdcfb758bac2379e185be8e092101d042eed72fd6"
  end

  def install
    bin.install cached_download => "zero"
    chmod 0755, bin/"zero"
  end

  def caveats
    <<~EOS
      Installs the ZERO CLI only. The public runtime defaults to paper mode.
      Release docs: https://github.com/zero-intel/zero/blob/main/docs/release.md
      Safety model: https://github.com/zero-intel/zero/blob/main/docs/safety-model.md
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zero --version")
  end
end
