#!/usr/bin/env python3
"""Generate the LLM full-context bundle from selected public docs."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "llms-full.txt"

SOURCES = (
    "README.md",
    "AGENTS.md",
    "CONTRIBUTING.md",
    "GOVERNANCE.md",
    "SECURITY.md",
    "docs/llms.txt",
    "docs/first-10-minutes.md",
    "docs/local-development.md",
    "docs/proof/README.md",
    "docs/architecture.md",
    "docs/cli-quickstart.md",
    "docs/api.md",
    "docs/api-compatibility.md",
    "docs/runtime-bus.md",
    "docs/safety-model.md",
    "docs/threat-model.md",
    "docs/incident-runbooks.md",
    "docs/open-core-boundary.md",
    "docs/production-readiness.md",
    "docs/public-upgrade.md",
    "docs/autonomous-os-plan.md",
    "docs/agentic-contribution.md",
    "docs/zero-network.md",
    "docs/zero-intelligence.md",
    "docs/model-gateway.md",
    "docs/release.md",
)


def render() -> str:
    parts = [
        "# ZERO LLM Full Context\n\n",
        "Generated by `scripts/generate_llms_full.py` from selected public docs.\n",
        "Use this bundle for retrieval and coding agents. It is not evidence of live trading readiness.\n\n",
        "## Sources\n\n",
    ]

    for rel in SOURCES:
        parts.append(f"- `{rel}`\n")

    for rel in SOURCES:
        path = ROOT / rel
        if not path.is_file():
            raise FileNotFoundError(rel)
        text = path.read_text(encoding="utf-8").rstrip()
        parts.append(f"\n\n## Source: `{rel}`\n\n````markdown\n{text}\n````\n")

    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()

    expected = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != expected:
            diff = difflib.unified_diff(
                current.splitlines(),
                expected.splitlines(),
                fromfile=str(OUTPUT),
                tofile="generated",
                lineterm="",
            )
            print("\n".join(list(diff)[:200]), file=sys.stderr)
            print("docs/llms-full.txt is stale; run scripts/generate_llms_full.py", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
