#!/usr/bin/env python3
"""Render a Homebrew formula from a verified ZERO release directory."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


FORMULA = '''# Generated by scripts/homebrew_formula.py.
# Do not publish until docs/distribution.md ownership gates pass.
class Zero < Formula
  desc "Operator terminal for self-custodial onchain operations"
  homepage "https://getzero.dev"
  license "Apache-2.0"
  version "{version}"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zero-intel/zero/releases/download/{tag}/zero-macos"
      sha256 "{macos_sha}"
    else
      odie "ZERO currently ships an arm64 macOS binary; build from source on Intel macOS"
    end
  end

  on_linux do
    url "https://github.com/zero-intel/zero/releases/download/{tag}/zero-linux"
    sha256 "{linux_sha}"
  end

  def install
    bin.install cached_download => "zero"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/zero --version")
  end
end
'''


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render Homebrew formula for ZERO release assets")
    parser.add_argument("release_dir", type=Path, help="Directory containing release assets and SHA256SUMS")
    parser.add_argument("--tag", required=True, help="Release tag, for example v0.1.1")
    parser.add_argument("--output", type=Path, help="Formula output path. Defaults to stdout.")
    return parser.parse_args()


def parse_checksums(path: Path) -> dict[str, str]:
    entries: dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw_line.strip():
            continue
        match = re.fullmatch(r"([a-fA-F0-9]{64})\s{2}(.+)", raw_line.strip())
        if not match:
            raise SystemExit(f"malformed checksum entry at line {line_number}")
        digest, name = match.groups()
        entries[name] = digest.lower()
    return entries


def version_from_tag(tag: str) -> str:
    if not re.fullmatch(r"v\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?", tag):
        raise SystemExit("tag must look like vMAJOR.MINOR.PATCH")
    return tag.removeprefix("v")


def main() -> int:
    args = parse_args()
    release_dir = args.release_dir.resolve()
    checksum_file = release_dir / "SHA256SUMS"
    if not checksum_file.is_file():
        raise SystemExit(f"missing checksum file: {checksum_file}")
    entries = parse_checksums(checksum_file)
    missing = [name for name in ("zero-linux", "zero-macos") if name not in entries]
    if missing:
        raise SystemExit(f"missing checksums for Homebrew assets: {', '.join(missing)}")

    formula = FORMULA.format(
        tag=args.tag,
        version=version_from_tag(args.tag),
        linux_sha=entries["zero-linux"],
        macos_sha=entries["zero-macos"],
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(formula, encoding="utf-8")
    else:
        print(formula, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
