#!/usr/bin/env python3
"""Build the public-safe demo proof pack."""

from __future__ import annotations

import argparse
import csv
import difflib
import hashlib
import json
from pathlib import Path
import shutil
import sys
import tempfile
from xml.sax.saxutils import escape

from zero_engine import JsonlCandleAdapter, PaperEngine, load_scenario

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "docs" / "proof" / "demo"
SCENARIO_PATH = ROOT / "examples" / "paper-trading" / "scenario.json"
CANDLES_PATH = ROOT / "examples" / "paper-trading" / "candles.jsonl"
PAPER_TS = 1777646400.0
GENERATED_AT = "2026-05-01T00:00:00Z"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return f"sha256:{digest.hexdigest()}"


def run_paper_scenario() -> dict:
    scenario = load_scenario(SCENARIO_PATH)
    market = JsonlCandleAdapter(CANDLES_PATH)
    engine = PaperEngine(limits=scenario.limits, clock=lambda: PAPER_TS)

    for order in scenario.orders:
        engine.submit(order, source=f"scenario:{scenario.name}")

    symbols = sorted({order.symbol for order in scenario.orders})
    return {
        "scenario": scenario.name,
        "mode": scenario.mode,
        "market": {
            symbol: {
                "as_of": market.latest(symbol).ts,
                "last": market.latest(symbol).close,
            }
            for symbol in symbols
        },
        "fills": len(engine.fills),
        "rejections": len(engine.rejections),
        "positions": {
            symbol: {
                "quantity": position.quantity,
                "avg_price": position.avg_price,
                "notional_usd": position.notional_usd,
            }
            for symbol, position in sorted(engine.positions.items())
        },
        "decisions": [record.to_dict() for record in engine.decisions],
    }


def write_decisions_csv(path: Path, paper: dict) -> None:
    fieldnames = (
        "as_of",
        "source",
        "symbol",
        "side",
        "quantity",
        "price",
        "notional_usd",
        "confidence",
        "reduce_only",
        "allowed",
        "reason",
    )
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for decision in paper["decisions"]:
            writer.writerow({key: decision[key] for key in fieldnames})


def write_svg(path: Path, paper: dict) -> None:
    decisions = len(paper["decisions"])
    fills = int(paper["fills"])
    rejections = int(paper["rejections"])
    fill_width = 320 * fills / decisions
    reject_width = 320 * rejections / decisions
    title = escape(f"ZERO demo proof pack: {paper['scenario']}")
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="760" height="300" role="img" aria-label="{title}">
  <rect width="760" height="300" fill="#f7f8f8"/>
  <text x="40" y="54" font-family="Arial, sans-serif" font-size="28" font-weight="700" fill="#111614">ZERO Demo Proof Pack</text>
  <text x="40" y="84" font-family="Arial, sans-serif" font-size="14" fill="#5d6864">Paper-only deterministic scenario. No live P&amp;L claim.</text>
  <text x="40" y="132" font-family="Arial, sans-serif" font-size="15" font-weight="700" fill="#111614">Decisions</text>
  <rect x="170" y="114" width="320" height="26" rx="4" fill="#d9dfdc"/>
  <rect x="170" y="114" width="{fill_width:.2f}" height="26" rx="4" fill="#0b6b53"/>
  <rect x="{170 + fill_width:.2f}" y="114" width="{reject_width:.2f}" height="26" fill="#8a4b1f"/>
  <text x="510" y="133" font-family="Arial, sans-serif" font-size="14" fill="#111614">{decisions} total</text>
  <text x="40" y="180" font-family="Arial, sans-serif" font-size="15" font-weight="700" fill="#111614">Paper fills</text>
  <text x="170" y="180" font-family="Arial, sans-serif" font-size="15" fill="#111614">{fills}</text>
  <text x="40" y="214" font-family="Arial, sans-serif" font-size="15" font-weight="700" fill="#111614">Paper rejections</text>
  <text x="170" y="214" font-family="Arial, sans-serif" font-size="15" fill="#111614">{rejections}</text>
  <text x="40" y="248" font-family="Arial, sans-serif" font-size="15" font-weight="700" fill="#111614">Live correlation</text>
  <text x="170" y="248" font-family="Arial, sans-serif" font-size="15" fill="#8a4b1f">unavailable until exchange evidence is attached</text>
</svg>
"""
    path.write_text(svg, encoding="utf-8")


def write_demo_readme(path: Path) -> None:
    path.write_text(
        """# ZERO Demo Proof Pack

This directory is generated by `scripts/proof_pack.py`.

It is a deterministic paper-mode proof pack for repository launch readiness.
It is not a paper-vs-live P&L correlation claim and does not imply live trading
profitability.

Verify it with:

```bash
PYTHONPATH="$PWD/engine/src" scripts/proof_pack.py --check
```
""",
        encoding="utf-8",
    )


def build(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    paper = run_paper_scenario()

    decisions_csv = output_dir / "paper-decisions.csv"
    proof_svg = output_dir / "paper-proof.svg"
    demo_readme = output_dir / "README.md"
    manifest = output_dir / "proof-pack.json"

    write_decisions_csv(decisions_csv, paper)
    write_svg(proof_svg, paper)
    write_demo_readme(demo_readme)

    artifacts = {
        "paper_decisions_csv": sha256_file(decisions_csv),
        "paper_proof_svg": sha256_file(proof_svg),
        "demo_readme": sha256_file(demo_readme),
        "scenario_json": sha256_file(SCENARIO_PATH),
        "candles_jsonl": sha256_file(CANDLES_PATH),
    }
    payload = {
        "schema_version": "zero.proof_pack.v1",
        "generated_at": GENERATED_AT,
        "name": "demo-paper-launch-smoke",
        "mode": "paper",
        "claim_boundary": {
            "paper_mode_verified": True,
            "live_trading_claimed": False,
            "paper_vs_live_correlation_claimed": False,
            "pnl_claimed": False,
        },
        "paper": {
            "scenario": paper["scenario"],
            "decisions": len(paper["decisions"]),
            "fills": paper["fills"],
            "rejections": paper["rejections"],
            "open_positions": len(paper["positions"]),
            "symbols": sorted(paper["market"].keys()),
        },
        "live_correlation": {
            "status": "unavailable",
            "reason": "requires signed paper/live records and exchange-side evidence",
            "r_squared": None,
        },
        "privacy": {
            "contains_exchange_credentials": False,
            "contains_wallet_material": False,
            "contains_raw_exchange_order_ids": False,
            "contains_private_notes": False,
        },
        "artifacts": artifacts,
    }
    encoded = json.dumps(payload, indent=2, sort_keys=True).encode("utf-8")
    payload["proof_hash"] = f"sha256:{hashlib.sha256(encoded).hexdigest()}"
    manifest.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def compare_dirs(current: Path, expected: Path) -> int:
    status = 0
    paths = sorted({path.relative_to(current) for path in current.rglob("*") if path.is_file()})
    paths.extend(
        path.relative_to(expected)
        for path in expected.rglob("*")
        if path.is_file() and path.relative_to(expected) not in paths
    )
    for rel in sorted(set(paths)):
        left = current / rel
        right = expected / rel
        left_text = left.read_text(encoding="utf-8") if left.exists() else ""
        right_text = right.read_text(encoding="utf-8") if right.exists() else ""
        if left_text == right_text:
            continue
        status = 1
        diff = difflib.unified_diff(
            left_text.splitlines(),
            right_text.splitlines(),
            fromfile=str(left),
            tofile=str(right),
            lineterm="",
        )
        print("\n".join(list(diff)[:200]), file=sys.stderr)
    return status


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated proof pack is stale")
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            expected = Path(tmp) / "demo"
            build(expected)
            status = compare_dirs(OUTPUT_DIR, expected)
            if status:
                print("docs/proof/demo is stale; run scripts/proof_pack.py", file=sys.stderr)
            return status

    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)
    build(OUTPUT_DIR)
    print(f"wrote {OUTPUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
